server:
  port: 8080

spring:
  datasource:
    username: root
    password: "Aapple,1"
    url: jdbc:mysql://localhost:3306/newstoday?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.YongAndJoe.NewsTodayBackend.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: jwtsecret
  validity: 86400 #24hr

config:
  filter:
    jwt-filter:
      ignore-paths: ["/acc/login", "/acc/register"]
  error-msgs:
    require-authentication: "Require Authentication"
    user-exist: "User already exist"
    user-not-exist: "User does not exist"
    login-failed: "Login failed"
    bad-request: "Bad request"
    require-username: "Username is required"
    require-password: "Password is required"
    require-email: "Email is required"
    email-format-invalid: "Email format XXXX@XXXX.com is required"
    password-too-short: "Password length needs be greater than 6"
